; ============================================================
; NTP Desk Clock — PlatformIO Configuration
; ============================================================

[env:feather_v2]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit GFX Library@^1.11.0
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.0
    https://github.com/tzapu/WiFiManager.git